import type { Metadata } from "next";
import {Smooch_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const smooch_sans = Smooch_Sans({
  subsets: ["latin"],
  weight:["400","500","600","700"],
  preload:true,
});



export const metadata: Metadata = {
  title: "FYLO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={smooch_sans.className }
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
